apps/web/src/__tests__/Studies.spec.tsx, apps/web/src/pages/studies/index.tsx
=> SE-22: SEO

apps/web/src/__tests__/Studies.spec.tsx, apps/web/src/components/molecules/Pagination/Pagination.tsx, apps/web/src/pages/studies/index.tsx, apps/web/src/utils/pagination.spec.ts, apps/web/src/utils/pagination.ts, packages/ui/globals.scss
=> SE-22: Studies list pagination fix

apps/web/src/__tests__/404.spec.tsx, apps/web/src/__tests__/500.spec.tsx, apps/web/src/components/Layout/RootLayout.tsx, apps/web/src/components/molecules/cards/GetSupport/GetSupport.tsx, apps/web/src/constants/content.ts, apps/web/src/pages/404.tsx, apps/web/src/pages/500.tsx, apps/web/src/pages/_document.tsx, apps/web/src/pages/index.tsx, apps/web/src/pages/organisations/index.tsx, apps/web/src/pages/studies/index.tsx, packages/ui/globals.scss
- Use the "Assess progress of studies" service name as the h1 across all pages
- Fix Side Nav to be 100% height
- Increase page container width and adjust grid to make the sidebar sticky
=> chore: update page headings and sticky sidebar

.github/workflows/execute-scheduled-task.yml
change manual workflow to revert back to 6pm after triggering the task
=> change cronjob to 6pm

apps/web/src/__tests__/Assessment.spec.tsx, apps/web/src/lib/studies.ts, apps/web/src/pages/assessments/[studyId]/index.tsx, packages/database/prisma/schema.prisma
=> SE-29: AC2 Further information 

apps/web/src/__tests__/Organisation.spec.tsx, apps/web/src/__tests__/Studies.spec.tsx, apps/web/src/__tests__/Study.spec.tsx, apps/web/src/components/atoms/Form/TextInput/TextInput.spec.tsx, apps/web/src/components/atoms/Form/TextInput/TextInput.tsx, apps/web/src/lib/organisations.spec.ts, apps/web/src/lib/organisations.ts, apps/web/src/pages/assessments/[studyId]/index.tsx, apps/web/src/pages/organisations/[organisationId]/index.tsx, apps/web/src/pages/organisations/index.tsx, apps/web/src/pages/studies/[studyId]/index.tsx, apps/web/src/pages/studies/index.tsx, apps/web/src/utils/withServerSideProps.spec.ts, apps/web/src/utils/withServerSideProps.ts
=> feat: organisation details

apps/web/src/@types/auth.d.ts, apps/web/src/__tests__/Home.spec.tsx, apps/web/src/__tests__/auth/SignoutConfirmation.spec.tsx, apps/web/src/constants/routes.ts, apps/web/src/pages/api/auth/[...nextauth].spec.ts, apps/web/src/pages/api/auth/[...nextauth].ts, apps/web/src/pages/api/auth/__snapshots__/[...nextauth].spec.ts.snap, apps/web/src/pages/auth/signout/confirmation.tsx, apps/web/src/pages/auth/signout/index.tsx, apps/web/src/pages/index.tsx
Resolves [SE-149](https://nihr.atlassian.net/browse/SE-149)
=> fix: sign out confirm page

.github/workflows/deploy-ingest.yml, .github/workflows/deploy-notify.yml, .github/workflows/deploy.yml, .github/workflows/run-e2e-tests.yml, packages/qa/hooks/GlobalSetup.ts, packages/qa/tests/features/loginTests/loginTest.e2e.ts, packages/qa/tests/features/organisationDetailsTests/orgDetailsCoreTest.e2e.ts, packages/qa/utils/DbRequests.ts, packages/qa/utils/dbConfig.ts
Adding manual E2E workflow trigger 
Adding E2E workflow into CI/CD web app pipeline
Changing GH Action IP fetch methods across all deploy jobs
=> Updating Workflows

apps/web/package.json, apps/web/src/__tests__/Studies.spec.tsx, apps/web/src/components/molecules/cards/RequestSupport/RequestSupport.spec.tsx, apps/web/src/components/molecules/cards/RequestSupport/RequestSupport.tsx, apps/web/src/constants/export.ts, apps/web/src/constants/index.ts, apps/web/src/lib/organisations.spec.ts, apps/web/src/lib/organisations.ts, apps/web/src/lib/studies.ts, apps/web/src/mocks/organisations.ts, apps/web/src/mocks/studies.ts, apps/web/src/pages/api/export.spec.ts, apps/web/src/pages/api/export.ts, apps/web/src/pages/assessments/[studyId]/index.tsx, apps/web/src/pages/studies/[studyId]/index.tsx, apps/web/src/pages/studies/index.tsx, package-lock.json
https://nihr.atlassian.net/browse/CRNCC-1946
=> feat(SE-165): export studies

apps/web/src/__tests__/Study.spec.tsx, apps/web/src/pages/studies/[studyId]/index.tsx, packages/qa/hooks/CustomFixtures.ts, packages/qa/pages/StudiesPage.ts, packages/qa/pages/StudyDetailsPage.ts, packages/qa/pages/StudyUpdatePage.ts, packages/qa/tests/features/studyDetailsTests/studyDetailsCoreTest.e2e.ts, packages/qa/tests/features/studyDetailsTests/studyDetailsSummaryTest.e2e.ts, packages/qa/tests/features/studyListTests/studyListBaselineTest.e2e.ts
- extends test coverage
- updates some copy inline with ac
- [SE-180](https://nihr.atlassian.net/browse/SE-180) & [SE-181](https://nihr.atlassian.net/browse/SE-181)
=> test: updates for SE-180, SE-181

apps/web/src/lib/studies.spec.ts, apps/web/src/pages/studies/[studyId]/index.tsx
[Ticket](https://nihr.atlassian.net/browse/SE-189)
This PR: 
- fixes the styling of the 'all studies link'
- fixes TS issue in a unit test
=> SE-189: Styling all studies link

apps/web/src/__tests__/Study.spec.tsx, apps/web/src/pages/studies/[studyId]/index.tsx
This PR updates copy based on if it's a commercial study.
=> SE-181: Update copy 

apps/web/src/__tests__/Study.spec.tsx, apps/web/src/mocks/studies.ts, apps/web/src/pages/studies/[studyId]/index.tsx
This PR:
- updates mapping on study details page
- adds a test id
=> SE-181: Update mapping and add testId

.github/workflows/run-e2e-tests.yml, package-lock.json, packages/qa/README.md, packages/qa/package.json, packages/qa/pages/StudyDetailsPage.ts, packages/qa/pages/StudyUpdatePage.ts, packages/qa/tests/features/studyDetailsTests/studyDetailsCoreTest.e2e.ts, packages/qa/tests/features/studyDetailsTests/studyDetailsSummaryTest.e2e.ts, packages/qa/tests/features/studyUpdateTests/studyUpdateTest.e2e.ts, packages/qa/utils/ApiRequests.ts
Adds test coverage for:
- SE-180
- SE-181
- SE-166
Also updates some test data methods to use the se api instead of db
=> se e2e refactor and updates

apps/web/src/pages/studies/[studyId]/edit.tsx, apps/web/src/utils/editStudyForm.ts, apps/web/src/utils/schemas/study.schema.ts
This PR enables all edit fields.
=> SE-166: Enable all edit fields

apps/web/src/components/atoms/Form/RadioGroup/RadioGroup.tsx, apps/web/src/constants/editStudyForm.ts, apps/web/src/lib/studies.spec.ts, apps/web/src/lib/studies.ts, apps/web/src/pages/api/forms/editStudy.spec.ts, apps/web/src/pages/api/forms/editStudy.ts, apps/web/src/pages/studies/[studyId]/edit.tsx
This PR saves the CPMS status in state rather than the radio button status values.
=> SE-184: Save CPMS status in state

apps/web/src/__tests__/EditStudy.spec.tsx, apps/web/src/pages/studies/[studyId]/edit.tsx
This PR shows a generic error when there is a server error when editing a study.
=> SE-184: Show server error

apps/web/src/__tests__/Study.spec.tsx, apps/web/src/constants/forms.ts
This PR modifies the success message for when a proposed and direct change happens.
=> SE-184: Success message text change

apps/web/src/__tests__/EditStudy.spec.tsx, apps/web/src/constants/editStudyForm.ts, apps/web/src/lib/cpms/studies.spec.ts, apps/web/src/mocks/studies.ts, apps/web/src/pages/api/forms/editStudy.spec.ts, apps/web/src/pages/studies/[studyId]/edit.tsx, apps/web/src/utils/editStudyForm.ts, apps/web/src/utils/schemas/study.schema.ts
This PR adds restrictions to the date fields including dependencies on other fields. Also adds validation to uk recruitment target field.
=> SE-183: Add specific date restrictions and dependencies

apps/web/src/constants/editStudyForm.ts, apps/web/src/utils/editStudyForm.ts
This PR fixes a date validation issue with dates that can be in past or current day.
=> SE-183: Fix date val for past/current

.github/workflows/deploy.yml, .github/workflows/run-e2e-tests.yml, packages/qa/hooks/GlobalTeardown.ts, packages/qa/pages/StudyUpdatePage.ts, packages/qa/tests/features/studyUpdateTests/studyUpdateSubmitTest.e2e.ts, packages/qa/tests/features/studyUpdateTests/studyUpdateTest.e2e.ts, packages/qa/utils/DbRequests.ts, packages/qa/utils/dbConfig.ts
- refactors `utils/dbConfig` & `utils/dbRequest` to use connection pool
- reduces code repetition
- ensures IP rules are always removed on failures
- runs slack hooks for se work
=> e2e additional yaml changes

apps/web/src/@types/studies.ts, apps/web/src/lib/cpms/studies.spec.ts, apps/web/src/lib/cpms/studies.ts, apps/web/src/mocks/studies.ts
This PR fixes the mapping for uk target when sending data to CPMS
=> SE-183: Fix mapping for uk target

apps/web/src/lib/studies.ts, apps/web/src/pages/studies/[studyId]/index.tsx, packages/qa/pages/StudyUpdatePage.ts
This PR fixes going from suspended (with recruitment) to open (with recruitment) - ensuring it's an automatic change.
=> SE-184: Fix suspended to open 

packages/qa/pages/StudyDetailsPage.ts, packages/qa/pages/StudyUpdatePage.ts, packages/qa/tests/features/dueLogicTests/dueLogicCriteriaTest.e2e.ts, packages/qa/tests/features/studyDetailsTests/studyDetailsCoreTest.e2e.ts, packages/qa/tests/features/studyUpdateTests/studyUpdateSubmitTest.e2e.ts, packages/qa/tests/features/studyUpdateTests/studyUpdateTest.e2e.ts, packages/qa/tests/features/studyUpdateTests/studyUpdateValidationTest.e2e.ts
Adds test coverage for:
- [SE-183](https://nihr.atlassian.net/browse/SE-183)
- [SE-200](https://nihr.atlassian.net/browse/SE-200)
- plus other test fixes and improvements
=> e2e updates for se-183 & se-200

.github/workflows/deploy.yml
fixes the condition that was evaluating both failure and success as true
=> test: fixes pipeline e2e slack hook

apps/web/src/constants/auth.ts, apps/web/src/pages/api/auth/[...nextauth].ts, apps/web/src/pages/api/forms/organisation.ts, apps/web/src/pages/api/forms/registration.ts, apps/web/src/pages/api/forms/removeContact.ts, apps/web/src/pages/studies/index.tsx, packages/auth/src/auth-service.spec.ts, packages/auth/src/auth-service.ts, packages/auth/src/constants/constants.ts, packages/auth/src/handlers.ts, packages/auth/src/types/requests.ts, packages/auth/src/types/responses.ts
This PR pulls in latest main into se-phase-2.
=> Pull main into se-phase-2

packages/qa/pages/StudyUpdatePage.ts, packages/qa/pages/cpmsStudiesPage.ts, packages/qa/tests/features/dueLogicTests/dueLogicCriteriaTest.e2e.ts, packages/qa/tests/features/studyUpdateTests/studyUpdateSubmitTest.e2e.ts, packages/qa/tests/features/studyUpdateTests/studyUpdateWithCpmsTest.e2e.ts
- dynamically uses test data for due logic tests
- adds assertions for study updating message shown only on update
- add unique target values for more accurate study update assertions
=> e2e test maintenance

apps/web/src/__tests__/Study.spec.tsx, apps/web/src/pages/studies/[studyId]/index.tsx, packages/qa/pages/StudyDetailsPage.ts, packages/qa/tests/features/studyDetailsTests/studyDetailsCoreTest.e2e.ts
This PR updates the copy of the edit study button.
=> SE-209: Update edit study button

apps/web/src/components/molecules/EditHistory/utils.ts, apps/web/src/pages/studies/[studyId]/index.tsx, packages/qa/pages/StudyDetailsPage.ts
This PR adds a mapping for the status on the study details page.
=> SE-207: Map status on study details page

apps/web/src/__tests__/EditStudy.spec.tsx, apps/web/src/lib/cpms/studies.spec.ts, apps/web/src/utils/editStudyForm.ts, apps/web/src/utils/schemas/study.schema.ts, apps/web/src/utils/typeUtils.ts
This PR makes the uk recruitment target field mandatory on the edit study page.
=> SE-217: Make uk target mandatory 

apps/web/src/lib/cpms/studies.ts, apps/web/src/lib/studies.ts, apps/web/src/pages/api/forms/editStudy.ts, apps/web/src/pages/studies/[studyId]/edit.tsx, apps/web/src/pages/studies/[studyId]/index.tsx
This PR adds logs to the edit study API, server side calls for edit study and study details page.
=> SE-211: Add logs

packages/qa/playwright.config.ts, packages/qa/tests/features/studyUpdateTests/studyUpdateWithCpmsUpdateTest.e2e.ts
updates the edit function to use the correct input field in CPMS
=> test: fixes cpms target update

apps/web/src/__tests__/EditStudy.spec.tsx, apps/web/src/__tests__/Organisation.spec.tsx, apps/web/src/__tests__/Organisations.spec.tsx, apps/web/src/__tests__/Studies.spec.tsx, apps/web/src/components/molecules/Pagination/Pagination.spec.tsx, apps/web/src/components/molecules/Pagination/Pagination.tsx, apps/web/src/components/molecules/cards/StudyList/StudyList.tsx, apps/web/src/constants/editStudyForm.ts, apps/web/src/pages/assessments/[studyId]/index.tsx, apps/web/src/pages/organisations/[organisationId]/index.tsx, apps/web/src/pages/organisations/index.tsx, apps/web/src/pages/studies/[studyId]/edit.tsx, apps/web/src/pages/studies/index.tsx, apps/web/src/utils/Renderers/RichTextRenderer/RichTextRenderer.tsx, apps/web/src/utils/editStudyForm.ts, packages/ui/components/SideNav/SideNav.tsx, packages/ui/globals.scss
PR for [https://nihr.atlassian.net/browse/CRNCC-2452](url)
=> SE-2452-Accessibility-review-changes

.github/workflows/pull-request.yml, apps/ingest/Dockerfile, apps/notify/Dockerfile, apps/web/Dockerfile, apps/web/src/__tests__/Assessment.spec.tsx, apps/web/src/pages/api/export.spec.ts, apps/web/src/pages/api/export.ts, apps/web/src/pages/assessments/[studyId]/index.tsx, packages/qa/pages/AssessmentPage.ts, packages/ui/components/SideNav/SideNav.tsx
Pull in latest main to `se-phase-3` branch
=> Update se-phase-3 with latest main

packages/qa/pages/CommonItemsPage.ts, packages/qa/tests/features/footerTests/footerTest.e2e.ts
The Footer logic is being skipped because the Footer has not been created yet.
=> Added tests for footer validation

packages/qa/pages/OrganisationDetailsPage.ts, packages/qa/tests/features/organisationDetailsTests/addRemoveContactTest.e2e.ts, packages/templates/sponsor-engagement/email/__snapshots__/index.spec.ts.snap
This PR fixes the E2E tests as part of SE-250. Another PR will be raised to update the E2E tests with the new functionality.
=> SE-250: Fix E2E tests

packages/qa/pages/OrganisationDetailsPage.ts
This PR fixes an E2E test associated with the work completed in SE-250.
=> fix(e2e): test

packages/qa/pages/CommonItemsPage.ts, packages/qa/pages/OrganisationDetailsPage.ts, packages/qa/tests/features/organisationDetailsTests/lastLoginTest.e2e.ts
The test checks if the last login date column exists and then checks if the date is in the correct format or a hyphen.
=> Last login date E2E test/se 250

.github/workflows/deploy-invitation-monitor.yml, .github/workflows/execute-scheduled-task.yml, .github/workflows/pull-request.yml, apps/invitation-monitor/.aws/task-definition-dev.json, apps/invitation-monitor/.aws/task-definition-oat.json, apps/invitation-monitor/.aws/task-definition-prod.json, apps/invitation-monitor/.aws/task-definition-test.json, apps/invitation-monitor/.aws/task-definition-uat.json, apps/invitation-monitor/Dockerfile, apps/invitation-monitor/README.md, apps/invitation-monitor/package.json
This PR adds task definitions and workflow files for the new app `invitation-monitor`.
=> SE-251: add task definitions and workflow files

apps/web/src/components/molecules/cards/StudyList/StudyList.tsx
=> Fix: Due tag alignment

apps/web/src/pages/index.tsx
https://nihr.atlassian.net/browse/CRNCC-2410
adding logout button from solution 2.
=> feat: adding logout button to home page
