apps/web/src/__tests__/Home.spec.tsx, apps/web/src/components/organisms/Layout/RootLayout.tsx, apps/web/src/pages/api/auth/[...nextauth].spec.ts, apps/web/src/pages/api/auth/[...nextauth].ts, apps/web/src/pages/index.tsx
https://nihr.atlassian.net/browse/SE-187
- Added graceful handling for when an IDG user logs in with no associated User record in the SE database
- Fixed two instances where errors could be swallowed during the auth flow
- Fixed idle timeout triggering unintentionally on auth unhappy paths
Before:
After:
=> fix(SE-187): improve auth flow when no user record in db

apps/web/src/pages/api/forms/registration.spec.ts, apps/web/src/pages/api/forms/registration.ts, apps/web/src/pages/register/index.tsx, apps/web/src/utils/schemas/registration.schema.ts
Include the user's first name and last name when registering a new account with Idg.
This is to fix an issue whereby users trying to reset their passwords were getting an error, due to not having a first and last name on their Idg account
=> feat: add Idg post firstName and lastName

apps/web/src/@types/studies.ts, apps/web/src/lib/studies.spec.ts, apps/web/src/lib/studies.ts, apps/web/src/pages/studies/[studyId]/edit.tsx
This PR:
- saves evals from CPMS to SE
- soft deletes evals in SE that were not returned from CPMS
=> SE-166: Save evals to SE

apps/ingest/src/ingest.ts, apps/ingest/src/mocks/studies.json, apps/ingest/src/tests/index.spec.ts, apps/ingest/src/types.ts, apps/web/src/__tests__/EditStudy.spec.tsx, apps/web/src/lib/studies.spec.ts, apps/web/src/lib/studies.ts, apps/web/src/mocks/studies.ts, apps/web/src/pages/api/forms/editStudy.ts, apps/web/src/pages/studies/[studyId]/edit.tsx, apps/web/src/pages/studies/[studyId]/index.tsx, apps/web/src/utils/editStudyForm.ts, apps/web/src/utils/schemas/study.schema.ts, packages/database/prisma/migrations/20240917085208_study_estimated_reopening_date/migration.sql, packages/database/prisma/schema.prisma
This PR:
- adds estimated reopening date to the SE Study schema
- adds a field for this on the edit study form and sends it through to CPMS
- stores this value from CPMS into SE DB on edit/study details page load
- updates ingest to also store this value from CPMS into SE
- includes a fix for displaying dates on study details page
This has been tested against a local mysql server.
=> SE-166: Estimated reopening date

apps/web/src/pages/studies/[studyId]/index.tsx, packages/qa/pages/StudyDetailsPage.ts, packages/qa/tests/features/studyDetailsTests/studyDetailsSummaryTest.e2e.ts
This PR changes the total recruitment label text depending on if a study is a commercial one.
=> SE-181: Update total recruitment label

apps/web/src/@types/studies.ts, apps/web/src/__tests__/Study.spec.tsx, apps/web/src/constants/forms.ts, apps/web/src/lib/cpms/studies.spec.ts, apps/web/src/lib/cpms/studies.ts, apps/web/src/mocks/studies.ts, apps/web/src/pages/api/forms/editStudy.spec.ts, apps/web/src/pages/api/forms/editStudy.ts, apps/web/src/pages/studies/[studyId]/index.tsx
This PR:
- calls the new validate study endpoint in CPMS
- uses the feature flag to control whether we treat the change as direct or proposed:
feature flag is **disabled** -> study update type is always proposed (therefore, no call to CPMS)
feature flag is **enabled** -> uses the response from the validate endpoint to determine the study update type
=> SE-184: Call validate endpoint

apps/web/src/__tests__/EditStudy.spec.tsx, apps/web/src/pages/studies/[studyId]/edit.tsx
This PR removes the hints for uk recruitment target and status.
=> SE-166: Remove input hints

apps/web/src/lib/studies.ts, apps/web/src/pages/api/forms/editStudy.spec.ts, apps/web/src/pages/api/forms/editStudy.ts, apps/web/src/pages/studies/[studyId]/edit.tsx, packages/database/prisma/migrations/20240924120515_study_updates_status/migration.sql, packages/database/prisma/schema.prisma
This PR: 
- adds a new field to the StudyUpdates table named `StudyStatusGroup` which is now mandatory (migration file includes deletion of records in that table)
- makes the existing `StudyStatus` field within this table optional
If proposed change, mapped CPMS status gets sent to validate endpoint but we only save form status in SE.
If direct change, mapped CPMS status get sent to validate endpoint AND saved in SE alongside form status.
=> SE-184: Save StudyStatusGroup

apps/web/src/@types/studies.ts, apps/web/src/__tests__/EditStudy.spec.tsx, apps/web/src/__tests__/Study.spec.tsx, apps/web/src/constants/editStudyForm.ts, apps/web/src/lib/studies.ts, apps/web/src/mocks/studies.ts, apps/web/src/utils/editStudyForm.ts, apps/web/src/utils/schemas/study.schema.ts
This PR:
- updates the Status enum for CPMS statuses and uses it for the mappings
- adds in logic for mandatory date fields. Most of them all rely on the current status, however there are two exceptions which rely on what the previous status was
=> SE-183: Add mandatory date fields logic

apps/web/src/__tests__/EditStudy.spec.tsx, apps/web/src/components/atoms/Form/DateInput/DateInput.spec.tsx, apps/web/src/components/atoms/Form/DateInput/DateInput.tsx, apps/web/src/lib/cpms/studies.spec.ts, apps/web/src/pages/api/forms/editStudy.spec.ts, apps/web/src/pages/studies/[studyId]/edit.tsx, apps/web/src/utils/date.ts, apps/web/src/utils/editStudyForm.ts, apps/web/src/utils/schemas/study.schema.ts
This PR:
- updates the basic date validation
- updates type=number fields to type=text based on this GDS [blog](https://technology.blog.gov.uk/2020/02/24/why-the-gov-uk-design-system-team-changed-the-input-type-for-numbers/) which explains the issues with type=number
=> Se-183: Update date validation 

apps/web/src/utils/editStudyForm.ts
This PR sets the default value of uk recruitment target to an empty string rather than undefined which the schema throws an error for.
=> SE-183: Fix target default value

apps/web/src/constants/forms.ts, apps/web/src/lib/cpms/studies.ts, apps/web/src/pages/api/forms/editStudy.spec.ts, apps/web/src/pages/api/forms/editStudy.ts
This PR sends a `notes` attribute when editing a study - specifically when a status has changed to Suspended.
=> Se-183: Send notes when editing study

apps/web/src/__tests__/EditStudy.spec.tsx, apps/web/src/__tests__/Study.spec.tsx, apps/web/src/lib/studies.spec.ts, apps/web/src/lib/studies.ts, apps/web/src/pages/studies/[studyId]/edit.tsx, apps/web/src/pages/studies/[studyId]/index.tsx, package-lock.json, packages/shared-utilities/package.json, packages/shared-utilities/src/lib/setStudyAssessmentDue/index.ts, packages/shared-utilities/src/lib/setStudyAssessmentDue/setStudyAssessmentDue.spec.ts
This PR:
- fixes warning text when saving a study
- sets isDueAssessment flag when we pull data from CPMS and save to SE
There is a separate function which sets the is due flag to true if required.
=> SE-167: Fix due assessment logic and warning text

apps/web/package.json, apps/web/src/__tests__/EditStudy.spec.tsx, apps/web/src/constants/editStudyForm.ts, apps/web/src/constants/identifiers.ts, apps/web/src/lib/studyUpdates.ts, apps/web/src/pages/api/forms/editStudy.spec.ts, apps/web/src/pages/api/forms/editStudy.ts, apps/web/src/pages/studies/[studyId]/edit.tsx, apps/web/src/utils/editStudyForm.ts, apps/web/src/utils/schemas/study.schema.ts, package-lock.json, packages/database/prisma/migrations/20241011092956_study_updates_state_transaction/migration.sql, packages/database/prisma/schema.prisma
This PR:
- updates the StudyUpdates to include two new fields `transactionId` and `studyUpdateState`
- ensures that two entries are logged in the table (one for before and after)
Follow up PR needs to pass through the correct LSN values
=> SE-168: Update StudyUpdates schema and edit logic

apps/web/src/pages/studies/[studyId]/edit.tsx
This PR passes in user organisation ids when fetching study to ensure users can only access studies that are part of their organisation.
=> SE-121: Check user organisation on edit page

apps/web/src/components/molecules/EditHistory/EditHistoryChangeText/utils.ts, apps/web/src/lib/cpms/studies.ts, apps/web/src/pages/api/forms/editStudy.spec.ts, apps/web/src/pages/api/forms/editStudy.ts
This PR sends the current lsn to the cpms endpoint when editing a study.
=> Send CurrentLsn to CPMS when editing study 

apps/web/src/pages/studies/[studyId]/edit.tsx
This PR fixes a UX issue when the page jumps due to error messages appearing. 
To prevent the sight of this, we scroll to the top of the page.
=> SE-216: Fix page jumpiness on errors

.github/workflows/deploy.yml, .github/workflows/run-e2e-tests.yml, packages/qa/.env.example, packages/qa/README.md, packages/qa/package.json, packages/qa/pages/LoginPage.ts, packages/qa/pages/StudyDetailsPage.ts, packages/qa/pages/StudyUpdatePage.ts, packages/qa/tests/features/studyDetailsTests/studyDetailsSummaryTest.e2e.ts, packages/qa/tests/features/studyUpdateTests/studyUpdateSubmitTest.e2e.ts, packages/qa/tests/features/studyUpdateTests/studyUpdateValidationTest.e2e.ts, packages/qa/tests/features/studyUpdateTests/studyUpdateWithCpmsTest.e2e.ts, packages/qa/utils/dbConfig.ts
- adds new tests for study edit history added & updated for proposed and direct changes
- un skips new validation tests for uk target
- enforces unique studies for update tests to avoid se cpms conflicts
- paramaterises test users and all db configs
=> se phase 2 e2e wrap up pr v1

apps/notify/src/notify.ts, apps/notify/src/tests/notify.spec.ts
This PR ensures we do not include deleted organisations in the notify email.
=> Do not include deleted organisations for notify email

.github/workflows/deploy.yml, .github/workflows/run-e2e-tests.yml, packages/qa/.env.example, packages/qa/README.md, packages/qa/hooks/GlobalTeardown.ts, packages/qa/package.json, packages/qa/tests/authSetup/auth.setup.e2e.ts, packages/qa/tests/features/accessibilityTests/axeAccessibilityTests.e2e.ts, packages/qa/utils/dbConfig.ts
- updates use of `CPMS_TEST_DB_IP` to `CPMS_TEST_DB_HOST`
- removes node options for deprecation note
- removes internal dev language from readme and examples
- updates gdpr cookie method
=> e2e test clean up

apps/web/src/constants/identifiers.ts, apps/web/src/pages/api/forms/organisation.spec.ts, apps/web/src/pages/api/forms/organisation.ts, packages/database/prisma/migrations/20250331133456_user_organisation_invitations/migration.sql, packages/database/prisma/schema.prisma
This PR:
- creates `UserOrganisationInvitation` table
- updates the API that adds a user to organisation, to create an entry in the new table and log the `messageId`
=> SE-251: Create UserOrganisationInvitation table and update API

apps/web/src/__tests__/Organisation.spec.tsx, apps/web/src/constants/identifiers.ts, apps/web/src/lib/organisations.ts, apps/web/src/pages/api/forms/organisation.spec.ts, apps/web/src/pages/api/forms/organisation.ts, apps/web/src/pages/api/forms/removeContact.spec.ts, apps/web/src/pages/api/forms/removeContact.ts, apps/web/src/pages/organisations/[organisationId]/index.tsx, packages/database/prisma/migrations/20250404132009_updated_user_organisation_invitations/migration.sql, packages/database/prisma/schema.prisma
This PR:
- updates the `userOrganisationInvitation` table to include `isDeleted` and `sentBy` fields
- surfaces failed user invites to the UI
=> SE-251: Surface invite failures to the UI 

apps/web/src/__tests__/Organisations.spec.tsx, apps/web/src/lib/organisations.spec.ts, apps/web/src/lib/organisations.ts, apps/web/src/pages/organisations/index.tsx
This PR updates the search organisations functionality to allow for email addresses. It takes into considerations, if a user is deleted and if a user has been removed from that organisation.
=> SE-252: Update 'search organisation' functionality 

.github/workflows/execute-scheduled-task.yml, apps/invitation-monitor/src/invitation-monitor.ts, apps/invitation-monitor/src/lib/constants.ts, apps/invitation-monitor/src/tests/index.spec.ts
As part of this PR, the AWS common errors and `getMessageInsights` API errors have been split into two groups - retry-able and fatal errors.
https://docs.aws.amazon.com/ses/latest/APIReference-V2/API_GetMessageInsights.html#API_GetMessageInsights_Errors
https://docs.aws.amazon.com/ses/latest/APIReference-V2/CommonErrors.html
Retry-able:
InternalFailure
RequestAbortedException
RequestExpired
RequestTimeoutException
ServiceUnavailable
ThrottlingException
TooManyRequestsException
Fatal:
AccessDeniedException
ExpiredTokenException
IncompleteSignature
MalformedHttpRequestException
NotAuthorized
OptInRequired
UnrecognizedClientException
UnknownOperationException
ValidationError
BadRequestException
NotFoundException
RequestEntityTooLargeException
The PR also updates the invitation-monitor task …
=> SE-251: Update retry logic based on error type

.github/workflows/execute-scheduled-task.yml
Temporarily change UAT invitation-monitor job to run 15:00 UTC.
=> Fix: Update UAT workflow to UTC 

apps/invitation-monitor/src/invitation-monitor.ts, apps/invitation-monitor/src/lib/constants.ts
This PR resolves an issue where we are getting consistently rate limited when fetching message insights from AWS. 
This solution runs each request sequentially to reduce the chances of making more than 1 request per second. From running this locally with ~ 300 pending emails, rate limit was only hit once and the retry logic we have in place, prevented another rate limit. (Appreciate the server will likely run faster than my machine, but given the retry logic that is in place, I think we're safe to rely on that.) 
**Why?**
While exploring different strategies (e.g. batching and random delays before making request), we consistently hit AWS's rate limit of 1 request per second. Even with delay mechanisms and retry logic in place, the initial batch or group of requests often exceeded the …
=> SE-251: Run requests sequentially

apps/web/src/components/organisms/Layout/RootLayout.tsx
[CRNCC-2410](https://nihr.atlassian.net/browse/CRNCC-2410 )
added a fallback to the root layout, if the user has not been passed in, retrieve the user from the session.
=> fix: show user in header on error pages

apps/web/src/pages/contact-managers/index.tsx, packages/qa/pages/ContactManagersPage.ts, packages/qa/tests/features/contactManagerTests/ContactManagersCoreTest.e2e.ts
changed the display to use updated at, records are not fully removed and when a users is re-assigned contact manager the same record is updated.
e2e tests updated to use new field.
=> Feat/2630 manager contact managers- e2e test update

apps/web/src/__tests__/Study.spec.tsx, apps/web/src/components/molecules/StudyDetails/StudyDetails.spec.tsx, apps/web/src/components/molecules/StudyDetails/StudyDetails.tsx
https://nihr.atlassian.net/browse/CRNCC-2026
added conditional to the chief investigator role in the study details to hide the chief investigator if study route is commercial.
updated tests.
=> feat: hiding cheif investigater row for commercial studies
